### ISSUE TITLE
Extension getting closed on mouse click or tab switch

### ISSUE THREAD

**Issue by Nandika-A** [Nandika-A/EyeProtection#1]
On clicking anywhere on screen or tab switching, the extension should get minimized and only timer should get displayed. However, it gets closed and then timer restarts.

**Comment by LyubomirT** [comment]
@Nandika-A That's a browser limitation, extensions get closed whenever you click anywhere outside of it.

**Comment by Nandika-A** [comment]
> @Nandika-A That's a browser limitation, extensions get closed whenever you click anywhere outside of it.

We're facing a problem where the timer stops and the extension closes with a mouse click or tab switch. We need a solution to handle this so that the timer continues running.

**Comment by LyubomirT** [comment]
> > @Nandika-A That's a browser limitation, extensions get closed whenever you click anywhere outside of it.
> 
> Yes, but there should be some way so that the timer continues running and the user's work and break intervals are accurately tracked.

If that's the case, then my fix (in progress) for #2 is going to incorporate that as well, since the pull request won't work without this feature.
