### ISSUE TITLE
Browser notifications 

### ISSUE THREAD

**Issue by Nandika-A** [Nandika-A/EyeProtection#2]
Notifications about taking a break are now given in the application. Instead, they should be displayed on the browser

**Comment by LyubomirT** [comment]
Perhaps I can try this issue out, could you please elaborate a bit just so I can understand things better? Would be glad to contribute to your project!

**Comment by Nandika-A** [comment]
Hi @LyubomirT! Glad to hear you're excited about contributing to our project! Currently, the extension has a bug where the reminder to take a 20-second break is only displayed within the opened extension. Ideally, this reminder should appear as a pop-up notification in the browser. Let me know if you have any questions or need more details.

**Comment by LyubomirT** [comment]
@Nandika-A I think I should use a combination of code in background.js and content.js for that, thank you for the additional info. I'll begin working on the issue, please assign it to me if it's okay!

**Comment by Nandika-A** [comment]
> @Nandika-A I think I should use a combination of code in background.js and content.js for that, thank you for the additional info. I'll begin working on the issue, please assign it to me if it's okay!

Yes sure!
